# Synthwave Purple Theme for Powerlevel10k
# Source this AFTER ~/.p10k.zsh in your .zshrc
# Colors: Deep purple backgrounds, hot pink/magenta, cyan accents

# ========== SYNTHWAVE COLOR PALETTE ==========
# Background: #0d0221 (13, 2, 33)   -> Color 234/236
# Purple:     #9d4edd (157, 78, 221) -> Color 135
# Hot Pink:   #ff2a6d (255, 42, 109) -> Color 197
# Magenta:    #ff00ff (255, 0, 255)  -> Color 201
# Cyan:       #05d9e8 (5, 217, 232)  -> Color 44
# Electric:   #00fff9 (0, 255, 249)  -> Color 51
# Yellow:     #fae566 (250, 229, 102) -> Color 227

# ========== PROMPT CHAR COLORS ==========
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=135
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=197

# ========== DIRECTORY COLORS ==========
typeset -g POWERLEVEL9K_DIR_BACKGROUND=135
typeset -g POWERLEVEL9K_DIR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=189
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

# Directory types with synthwave colors
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=99
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=135
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=129
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND=197
typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND=255

# ========== GIT/VCS COLORS ==========
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=44
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=16
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=227
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=16
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=201
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=16
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=197
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=255
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=129
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=255

# ========== STATUS (exit code) ==========
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=44
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=16
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=44
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=16
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=197
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=255
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=197
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=255
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=197
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=255

# ========== COMMAND EXECUTION TIME ==========
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=129
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=255

# ========== BACKGROUND JOBS ==========
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=201
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=16

# ========== NODE/NVM ==========
typeset -g POWERLEVEL9K_NVM_BACKGROUND=44
typeset -g POWERLEVEL9K_NVM_FOREGROUND=16
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=44
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=16

# ========== PYTHON/VIRTUALENV ==========
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=227
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=16
typeset -g POWERLEVEL9K_PYENV_BACKGROUND=227
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=16

# ========== KUBERNETES ==========
typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=51
typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=16

# ========== AWS ==========
typeset -g POWERLEVEL9K_AWS_BACKGROUND=214
typeset -g POWERLEVEL9K_AWS_FOREGROUND=16

# ========== DOCKER ==========
typeset -g POWERLEVEL9K_DOCKER_BACKGROUND=39
typeset -g POWERLEVEL9K_DOCKER_FOREGROUND=16

# ========== CONTEXT (user@host) ==========
typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=197
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=255
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=135
typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=255
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=201
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=16

# ========== OS ICON ==========
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=236
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=135

# ========== TIME ==========
typeset -g POWERLEVEL9K_TIME_BACKGROUND=236
typeset -g POWERLEVEL9K_TIME_FOREGROUND=135

# ========== FRAME/DECORATIONS ==========
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

# ========== CUSTOM SEGMENT: Claude Code Indicator ==========
function prompt_claude_code() {
  if [[ -n "$CLAUDE_CODE_SESSION" ]]; then
    p10k segment -b 135 -f 255 -i '󰚩' -t 'Claude'
  fi
}

# ========== CUSTOM SEGMENT: Automaker Indicator ==========
function prompt_automaker() {
  if [[ -n "$AUTOMAKER_SESSION" ]]; then
    p10k segment -b 44 -f 16 -i '󰚀' -t 'Auto'
  fi
}

# Add custom segments to left prompt if desired
# Uncomment the following to add Claude/Automaker indicators:
# typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon claude_code automaker dir vcs newline prompt_char)

echo "Synthwave theme loaded"
